### PR TITLE
Overhauled music doc with GBT Player's readme info

### PR DESCRIPTION
**Pull request by DeerTears**
In this edit I go over the limits of GBT Player when it reads MOD files, and things it depends on for every MOD file.

I tested the range of the first 3 channels, using GB Studio's emulator along with mGBA to ensure these notes were still playable on emulated hardware. They are not limited to C3 like GBT's documentation says, but more investigation should still take place with note ranges.

### CODE REVIEW

**Comment by RichardULZ** [comment]
The pulse waves can use instruments 1-4 for 3 unique pulse width sounds,
Channel 3, the wave table, has a bunch of pre programmed waves to pick from, instruments 8-15, 
and same for the noise channel, instruments 16-31.

I think you have misinterpreted the gbt2mod documentation.

https://github.com/chrismaltby/gb-studio/issues/83#issuecomment-487410594

**Comment by chrismaltby** [comment]
This is definitely a very welcome and much needed pull request.

Before I merge though @RichardULZ from your comment it sounds like there's some inaccuracies maybe in this content, I'm not in the best position to say either way, is this something that can be worked out in the comments here or is it best to merge this now and people can submit pull requests to improve upon it later?

**Comment by chrismaltby** [comment]
@DeerTears also if you merge the latest master commit back into your request the checks should now pass and it should generate a dynamic deploy preview url on Netlify :-)

**Comment by DeerTears** [comment]
Wow cool, huge thanks for the helpful feedback

I'll remove/change the stuff I misread so at least the majority can get merged

**Comment by DeerTears** [comment]
Alright @RichardULZ @chrismaltby how's this?

**Comment by DeerTears** [comment]
Unrelated but I just saw that the table styling kinda messes with the headers, but I'll wait to try to change anything with that image

**Comment by RichardULZ** [comment]
You have documentation on set tick speed the opposite way, 
tick speed F01 should be fastest (new note every frame) and F1F slowest, (tick every 32 frames).

The speed differs slightly as trackers work at 50fps, and gbt2mod tries its best to convert these numbers to 60fps.

I'm still doing investigation, but i think although volume is from C00 to C40, it may only have 16 set volumes, so C04, C08, C0C, C10 etc...

Changing the volume on channel 3 requires the sample and note to be set, and can only be set to C40, C20, C10, and C00.

I think this was missed in the default template music, which does not fade out like in the mod. @chrismaltby

**Comment by DeerTears** [comment]
Alright, hopefully this commit doesn't have any conflicting information with what's currently being figured out

**Comment by RichardULZ** [comment]
Putting this here to keep track of it.

https://gist.github.com/ARival @ARival
A reformatted list of mod_instructions.txt,
https://gist.github.com/ARival/877c341f2d449bba056b048bcb91a065

@ARival also made minor improvements to an instrument cheat sheet by @DeerTears 
https://gist.github.com/ARival/fd9f0640635e195d66dcc313ef0ec904

There are some wave channel preview images in the discord Share your work channel too, but not all of them.
Wave Previews can also be easily extracted using wasmboy.app and previewing audio>Wavetable while running a rom.

**Comment by ARival** [comment]
https://observablehq.com/d/2122ddb47335773f

Here is my source code for reading the Waveforms. You can extract the PNGs directly from this page.

**Pull request merged**
