### PR TITLE
Localization of Documentation [GERMAN]

### PR DESCRIPTION
**Pull request by locherunderscore**
I hope that my german localization attempt of the website documentation will prove to be useful to someone someday.  
I translated everything under `content/docs/` and placed these files in another folder.

### CODE REVIEW

**Comment by chrismaltby** [comment]
Had to make a few small changes to hook this up in Hugo (/doku became /docs again sorry) but it's live now at https://www.gbstudio.dev/de/docs

Thank you so much for all the effort required to make this localisation. I know how much work it must have been because I wrote all the English pages!!

**Comment by RichardULZ** [comment]
That's pretty awesome. 
I hope this doesn't come across as insensitive, but would it be worth keeping the English names for URLs so it's easy to switch languages? By adding or removing /de anywhere?
So with
www.gbstudio.dev/docs/installation/ 
www.gbstudio.dev/de/docs/speichern-laden/   would become 
www.gbstudio.dev/de/docs/installation/ 
They would keep their translated names on links and page headers.

Being able to swap and compare translations quickly would be helpful, and may cause less confusion in the long run if more translations are added.

**Comment by chrismaltby** [comment]
That's a good idea, managed to do this while still keeping the German urls by adding aliases from the English urls to the de translation if you add /de in commit 8df4bcf340c0ed11ad372ff270d07b09b104f762

Looks like Hugo has quite a few options for handling localisation that could help as this grows
https://gohugo.io/content-management/multilingual/
Using `translationKey` it looks like it would be possible to add an automatically generated link to all the translated versions of a single page at some point. (at the moment I've just hard coded a link on the index page)

**Comment by RichardULZ** [comment]
Good start, although it doesn't go backwards from German to English. 
Might be easier to leave that for hugo or something down the line.

**Pull request merged**
