### PR TITLE
Adding 2.0.0 collision/colorize tool info for Project-Editor.md and Keyboard-Shortcuts.md

### PR DESCRIPTION
**Pull request by DeerTears**
I had a hard time knowing what to call the "tile-painting" mode but I noticed that it was previously mentioned as "drawing" so I just called it "drawing mode"

Also originally this page only talked about "Select mode" and I felt like that wasn't suitable for the fact that it came from the "Editor toolbar" so I've switched to calling it the "Select tool", "Add tool", "Collisions tool" - which now enables "drawing mode". I hope this wording makes enough sense, or if I'm secretly breaking a UX convention and I should revert what I did to the naming conventions.

I also hope you don't mind that I changed some of the old wording so the first parts of most sentences are about use case, rather than starting off as instructions that aren't made clear as to what they will be doing first.

### CODE REVIEW

**Comment by RichardULZ** [comment]
Note about Shift key to paint a line from last point, or hold to draw straight lines. 
Note about holding shift to combine collision types.
Note about long pressing a colour palette in drawing mode to change or edit the default palette.

**Comment by DeerTears** [comment]
Oh thanks, I really should've talked about this more first with others but I guess I didn't intend for keyboard shortcuts to be part of this pr until I overstepped my original scope. Will update accordingly though, thanks

**Comment by RichardULZ** [comment]
Nice, can you think of any neat/nice way to mention that in the scene editor page too? Perhaps it's up to screenshots... 
Looks good so far though

**Comment by DeerTears** [comment]
I've been meaning to add new info to the scene editor page but I've been too booked to write it of late. I may be able to get to that in a few days. **If Chris can hold-off on accepting this PR until an edit to the scene editor page is added to my branch, that'd be helpful.**

**Comment by DeerTears** [comment]
This PR is ready whenever Chris is. c:

**Comment by chrismaltby** [comment]
Great stuff, thanks @DeerTears Sorry it took me a while to review this but it's all great and now merged into the beta docs

**Pull request merged**
